add_test( [==[Learner: 完整学习循环]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 完整学习循环]==]  )
set_tests_properties( [==[Learner: 完整学习循环]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 感知循环]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 感知循环]==]  )
set_tests_properties( [==[Learner: 感知循环]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 经验学习]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 经验学习]==]  )
set_tests_properties( [==[Learner: 经验学习]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 发展阶段]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 发展阶段]==]  )
set_tests_properties( [==[Learner: 发展阶段]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 能力评估]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 能力评估]==]  )
set_tests_properties( [==[Learner: 能力评估]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 自主进化]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 自主进化]==]  )
set_tests_properties( [==[Learner: 自主进化]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 统计]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 统计]==]  )
set_tests_properties( [==[Learner: 统计]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 保存和加载]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 保存和加载]==]  )
set_tests_properties( [==[Learner: 保存和加载]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ModuleRegistry: 注册并获取模块]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ModuleRegistry: 注册并获取模块]==]  )
set_tests_properties( [==[ModuleRegistry: 注册并获取模块]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ModuleRegistry: 未注册模块抛异常]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ModuleRegistry: 未注册模块抛异常]==]  )
set_tests_properties( [==[ModuleRegistry: 未注册模块抛异常]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ModuleRegistry: 直接设置实例]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ModuleRegistry: 直接设置实例]==]  )
set_tests_properties( [==[ModuleRegistry: 直接设置实例]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ModuleRegistry: has_factory 和 initialized_names]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ModuleRegistry: has_factory 和 initialized_names]==]  )
set_tests_properties( [==[ModuleRegistry: has_factory 和 initialized_names]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ModuleRegistry: clear_instances 保留工厂]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ModuleRegistry: clear_instances 保留工厂]==]  )
set_tests_properties( [==[ModuleRegistry: clear_instances 保留工厂]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 基本观察]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 基本观察]==]  )
set_tests_properties( [==[StatisticalLearner: 基本观察]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 概念涌现]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 概念涌现]==]  )
set_tests_properties( [==[StatisticalLearner: 概念涌现]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 概念查询]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 概念查询]==]  )
set_tests_properties( [==[StatisticalLearner: 概念查询]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 序列预测]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 序列预测]==]  )
set_tests_properties( [==[StatisticalLearner: 序列预测]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 意外度]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 意外度]==]  )
set_tests_properties( [==[StatisticalLearner: 意外度]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 关系涌现]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 关系涌现]==]  )
set_tests_properties( [==[StatisticalLearner: 关系涌现]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 相关概念]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 相关概念]==]  )
set_tests_properties( [==[StatisticalLearner: 相关概念]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[StatisticalLearner: 统计信息]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[StatisticalLearner: 统计信息]==]  )
set_tests_properties( [==[StatisticalLearner: 统计信息]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[UnifiedReasoningEngine: 基本推理]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[UnifiedReasoningEngine: 基本推理]==]  )
set_tests_properties( [==[UnifiedReasoningEngine: 基本推理]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[UnifiedReasoningEngine: 直接查询]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[UnifiedReasoningEngine: 直接查询]==]  )
set_tests_properties( [==[UnifiedReasoningEngine: 直接查询]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[UnifiedReasoningEngine: 概率推理]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[UnifiedReasoningEngine: 概率推理]==]  )
set_tests_properties( [==[UnifiedReasoningEngine: 概率推理]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[UnifiedReasoningEngine: 多跳推理]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[UnifiedReasoningEngine: 多跳推理]==]  )
set_tests_properties( [==[UnifiedReasoningEngine: 多跳推理]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[UnifiedReasoningEngine: 归纳推理]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[UnifiedReasoningEngine: 归纳推理]==]  )
set_tests_properties( [==[UnifiedReasoningEngine: 归纳推理]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[UnifiedReasoningEngine: 空知识图谱]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[UnifiedReasoningEngine: 空知识图谱]==]  )
set_tests_properties( [==[UnifiedReasoningEngine: 空知识图谱]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[UnifiedReasoningEngine: 关键词提取]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[UnifiedReasoningEngine: 关键词提取]==]  )
set_tests_properties( [==[UnifiedReasoningEngine: 关键词提取]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: 向量加法]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: 向量加法]==]  )
set_tests_properties( [==[TensorOps: 向量加法]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: 向量减法]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: 向量减法]==]  )
set_tests_properties( [==[TensorOps: 向量减法]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: 标量乘法]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: 标量乘法]==]  )
set_tests_properties( [==[TensorOps: 标量乘法]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: ReLU]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: ReLU]==]  )
set_tests_properties( [==[TensorOps: ReLU]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: MSE]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: MSE]==]  )
set_tests_properties( [==[TensorOps: MSE]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: 余弦相似度]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: 余弦相似度]==]  )
set_tests_properties( [==[TensorOps: 余弦相似度]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: 矩阵向量乘法]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: 矩阵向量乘法]==]  )
set_tests_properties( [==[TensorOps: 矩阵向量乘法]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: 外积更新]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: 外积更新]==]  )
set_tests_properties( [==[TensorOps: 外积更新]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TensorOps: clamp]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TensorOps: clamp]==]  )
set_tests_properties( [==[TensorOps: clamp]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[HippocampalMemory: 单次编码]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[HippocampalMemory: 单次编码]==]  )
set_tests_properties( [==[HippocampalMemory: 单次编码]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[HippocampalMemory: 按实体检索]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[HippocampalMemory: 按实体检索]==]  )
set_tests_properties( [==[HippocampalMemory: 按实体检索]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[HippocampalMemory: 容量限制]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[HippocampalMemory: 容量限制]==]  )
set_tests_properties( [==[HippocampalMemory: 容量限制]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[HippocampalMemory: 强度衰减]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[HippocampalMemory: 强度衰减]==]  )
set_tests_properties( [==[HippocampalMemory: 强度衰减]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[HippocampalMemory: 遗忘弱记忆]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[HippocampalMemory: 遗忘弱记忆]==]  )
set_tests_properties( [==[HippocampalMemory: 遗忘弱记忆]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[HippocampalMemory: 增强指定条目]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[HippocampalMemory: 增强指定条目]==]  )
set_tests_properties( [==[HippocampalMemory: 增强指定条目]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[HippocampalMemory: get_strongest]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[HippocampalMemory: get_strongest]==]  )
set_tests_properties( [==[HippocampalMemory: get_strongest]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[CorticalMemory: 存储和检索]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[CorticalMemory: 存储和检索]==]  )
set_tests_properties( [==[CorticalMemory: 存储和检索]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[CorticalMemory: 重复存储会增强]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[CorticalMemory: 重复存储会增强]==]  )
set_tests_properties( [==[CorticalMemory: 重复存储会增强]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[CorticalMemory: 衰减]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[CorticalMemory: 衰减]==]  )
set_tests_properties( [==[CorticalMemory: 衰减]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[SleepConsolidation: 完整睡眠周期]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[SleepConsolidation: 完整睡眠周期]==]  )
set_tests_properties( [==[SleepConsolidation: 完整睡眠周期]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[SleepConsolidation: 弱记忆被遗忘]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[SleepConsolidation: 弱记忆被遗忘]==]  )
set_tests_properties( [==[SleepConsolidation: 弱记忆被遗忘]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeExtractor: 提取中文实体]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeExtractor: 提取中文实体]==]  )
set_tests_properties( [==[KnowledgeExtractor: 提取中文实体]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeExtractor: 提取关系三元组]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeExtractor: 提取关系三元组]==]  )
set_tests_properties( [==[KnowledgeExtractor: 提取关系三元组]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeExtractor: 提取因果关系]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeExtractor: 提取因果关系]==]  )
set_tests_properties( [==[KnowledgeExtractor: 提取因果关系]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeExtractor: 提取数值事实]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeExtractor: 提取数值事实]==]  )
set_tests_properties( [==[KnowledgeExtractor: 提取数值事实]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeExtractor: 空文本]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeExtractor: 空文本]==]  )
set_tests_properties( [==[KnowledgeExtractor: 空文本]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeExtractor: 多个因果关系]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeExtractor: 多个因果关系]==]  )
set_tests_properties( [==[KnowledgeExtractor: 多个因果关系]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[PredictiveCodingEngine: 构造和基本预测]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[PredictiveCodingEngine: 构造和基本预测]==]  )
set_tests_properties( [==[PredictiveCodingEngine: 构造和基本预测]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[PredictiveCodingEngine: 学习降低误差]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[PredictiveCodingEngine: 学习降低误差]==]  )
set_tests_properties( [==[PredictiveCodingEngine: 学习降低误差]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[PredictiveCodingEngine: 好奇心]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[PredictiveCodingEngine: 好奇心]==]  )
set_tests_properties( [==[PredictiveCodingEngine: 好奇心]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[PredictiveCodingEngine: 学习进度初始为 0]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[PredictiveCodingEngine: 学习进度初始为 0]==]  )
set_tests_properties( [==[PredictiveCodingEngine: 学习进度初始为 0]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[PredictiveCodingEngine: 状态保存和加载]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[PredictiveCodingEngine: 状态保存和加载]==]  )
set_tests_properties( [==[PredictiveCodingEngine: 状态保存和加载]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[PredictiveCodingEngine: 推理步数记录]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[PredictiveCodingEngine: 推理步数记录]==]  )
set_tests_properties( [==[PredictiveCodingEngine: 推理步数记录]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 从简单文本学习]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 从简单文本学习]==]  )
set_tests_properties( [==[TextLearner: 从简单文本学习]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 从因果文本学习]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 从因果文本学习]==]  )
set_tests_properties( [==[TextLearner: 从因果文本学习]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 从数值文本学习]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 从数值文本学习]==]  )
set_tests_properties( [==[TextLearner: 从数值文本学习]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 学后思考]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 学后思考]==]  )
set_tests_properties( [==[TextLearner: 学后思考]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: STDP 连接]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: STDP 连接]==]  )
set_tests_properties( [==[TextLearner: STDP 连接]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 海马记忆]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 海马记忆]==]  )
set_tests_properties( [==[TextLearner: 海马记忆]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 知识图谱增长]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 知识图谱增长]==]  )
set_tests_properties( [==[TextLearner: 知识图谱增长]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 验证反馈]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 验证反馈]==]  )
set_tests_properties( [==[TextLearner: 验证反馈]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[TextLearner: 矛盾检测]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[TextLearner: 矛盾检测]==]  )
set_tests_properties( [==[TextLearner: 矛盾检测]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[EpisodicMemory: 存储和检索]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[EpisodicMemory: 存储和检索]==]  )
set_tests_properties( [==[EpisodicMemory: 存储和检索]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[EpisodicMemory: 容量限制]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[EpisodicMemory: 容量限制]==]  )
set_tests_properties( [==[EpisodicMemory: 容量限制]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[EpisodicMemory: 巩固]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[EpisodicMemory: 巩固]==]  )
set_tests_properties( [==[EpisodicMemory: 巩固]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ActivationSpread: 简单扩散]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ActivationSpread: 简单扩散]==]  )
set_tests_properties( [==[ActivationSpread: 简单扩散]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ActivationSpread: 衰减效应]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ActivationSpread: 衰减效应]==]  )
set_tests_properties( [==[ActivationSpread: 衰减效应]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[ActivationSpread: 阈值过滤]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[ActivationSpread: 阈值过滤]==]  )
set_tests_properties( [==[ActivationSpread: 阈值过滤]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[STDP: LTP 长时程增强]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[STDP: LTP 长时程增强]==]  )
set_tests_properties( [==[STDP: LTP 长时程增强]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[STDP: LTD 长时程抑制]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[STDP: LTD 长时程抑制]==]  )
set_tests_properties( [==[STDP: LTD 长时程抑制]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[STDP: 强连接检索]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[STDP: 强连接检索]==]  )
set_tests_properties( [==[STDP: 强连接检索]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[STDP: 全局衰减]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[STDP: 全局衰减]==]  )
set_tests_properties( [==[STDP: 全局衰减]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Perception: MultiModalEncoder 构造与基本编码]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Perception: MultiModalEncoder 构造与基本编码]==]  )
set_tests_properties( [==[Perception: MultiModalEncoder 构造与基本编码]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Perception: 单模态编码]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Perception: 单模态编码]==]  )
set_tests_properties( [==[Perception: 单模态编码]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Perception: 多模态融合编码]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Perception: 多模态融合编码]==]  )
set_tests_properties( [==[Perception: 多模态融合编码]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Perception: 权重更新]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Perception: 权重更新]==]  )
set_tests_properties( [==[Perception: 权重更新]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Perception: 空输入返回零向量]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Perception: 空输入返回零向量]==]  )
set_tests_properties( [==[Perception: 空输入返回零向量]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Environment: SimpleEnvironment 初始化]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Environment: SimpleEnvironment 初始化]==]  )
set_tests_properties( [==[Environment: SimpleEnvironment 初始化]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Environment: step 执行动作]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Environment: step 执行动作]==]  )
set_tests_properties( [==[Environment: step 执行动作]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Environment: reset 重置环境]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Environment: reset 重置环境]==]  )
set_tests_properties( [==[Environment: reset 重置环境]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Environment: 到达目标获得高奖励]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Environment: 到达目标获得高奖励]==]  )
set_tests_properties( [==[Environment: 到达目标获得高奖励]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Environment: configure_for_stage 调整难度]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Environment: configure_for_stage 调整难度]==]  )
set_tests_properties( [==[Environment: configure_for_stage 调整难度]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Autonomous: Learner 在环境中自主学习]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Autonomous: Learner 在环境中自主学习]==]  )
set_tests_properties( [==[Autonomous: Learner 在环境中自主学习]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Autonomous: 自主学习降低预测误差]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Autonomous: 自主学习降低预测误差]==]  )
set_tests_properties( [==[Autonomous: 自主学习降低预测误差]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Autonomous: 巩固在循环中执行]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Autonomous: 巩固在循环中执行]==]  )
set_tests_properties( [==[Autonomous: 巩固在循环中执行]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Social: SocialAgent 交互]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Social: SocialAgent 交互]==]  )
set_tests_properties( [==[Social: SocialAgent 交互]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Social: 观察伙伴学习]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Social: 观察伙伴学习]==]  )
set_tests_properties( [==[Social: 观察伙伴学习]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Social: 教授其他 Agent]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Social: 教授其他 Agent]==]  )
set_tests_properties( [==[Social: 教授其他 Agent]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Social: 接收知识]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Social: 接收知识]==]  )
set_tests_properties( [==[Social: 接收知识]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Social: 统计信息]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Social: 统计信息]==]  )
set_tests_properties( [==[Social: 统计信息]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Persistence: save 和 load 状态]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Persistence: save 和 load 状态]==]  )
set_tests_properties( [==[Persistence: save 和 load 状态]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Persistence: 保存文件格式正确]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Persistence: 保存文件格式正确]==]  )
set_tests_properties( [==[Persistence: 保存文件格式正确]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Grounding: 感知聚类创建]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Grounding: 感知聚类创建]==]  )
set_tests_properties( [==[Grounding: 感知聚类创建]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Grounding: 相似感知合并到同一聚类]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Grounding: 相似感知合并到同一聚类]==]  )
set_tests_properties( [==[Grounding: 相似感知合并到同一聚类]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Grounding: 社会标注接地]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Grounding: 社会标注接地]==]  )
set_tests_properties( [==[Grounding: 社会标注接地]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Grounding: 重复社会标注增强置信度]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Grounding: 重复社会标注增强置信度]==]  )
set_tests_properties( [==[Grounding: 重复社会标注增强置信度]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Grounding: 相似概念检索]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Grounding: 相似概念检索]==]  )
set_tests_properties( [==[Grounding: 相似概念检索]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Grounding: 未接地符号返回空]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Grounding: 未接地符号返回空]==]  )
set_tests_properties( [==[Grounding: 未接地符号返回空]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Development: 初始阶段为感知运动]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Development: 初始阶段为感知运动]==]  )
set_tests_properties( [==[Development: 初始阶段为感知运动]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Development: 预测准确率达标可晋升]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Development: 预测准确率达标可晋升]==]  )
set_tests_properties( [==[Development: 预测准确率达标可晋升]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Development: 词汇量达标可晋升]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Development: 词汇量达标可晋升]==]  )
set_tests_properties( [==[Development: 词汇量达标可晋升]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Development: 条件不足不能晋升]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Development: 条件不足不能晋升]==]  )
set_tests_properties( [==[Development: 条件不足不能晋升]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Development: 逐级晋升到读写]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Development: 逐级晋升到读写]==]  )
set_tests_properties( [==[Development: 逐级晋升到读写]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Development: 阶段转换记录历史]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Development: 阶段转换记录历史]==]  )
set_tests_properties( [==[Development: 阶段转换记录历史]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Development: 阶段名称转换]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Development: 阶段名称转换]==]  )
set_tests_properties( [==[Development: 阶段名称转换]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Evolver: 能力评估返回所有能力]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Evolver: 能力评估返回所有能力]==]  )
set_tests_properties( [==[Evolver: 能力评估返回所有能力]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Evolver: 进化后分数应记录]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Evolver: 进化后分数应记录]==]  )
set_tests_properties( [==[Evolver: 进化后分数应记录]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Evolver: 弱项识别]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Evolver: 弱项识别]==]  )
set_tests_properties( [==[Evolver: 弱项识别]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[SimulationReasoning: 场景构建]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[SimulationReasoning: 场景构建]==]  )
set_tests_properties( [==[SimulationReasoning: 场景构建]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[SimulationReasoning: 因果链追踪]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[SimulationReasoning: 因果链追踪]==]  )
set_tests_properties( [==[SimulationReasoning: 因果链追踪]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[SimulationReasoning: 反事实推理]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[SimulationReasoning: 反事实推理]==]  )
set_tests_properties( [==[SimulationReasoning: 反事实推理]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[SimulationReasoning: 表达为自然语言]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[SimulationReasoning: 表达为自然语言]==]  )
set_tests_properties( [==[SimulationReasoning: 表达为自然语言]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[SimulationReasoning: 统计]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[SimulationReasoning: 统计]==]  )
set_tests_properties( [==[SimulationReasoning: 统计]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeVerifier: 验证通过]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeVerifier: 验证通过]==]  )
set_tests_properties( [==[KnowledgeVerifier: 验证通过]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeVerifier: 验证失败]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeVerifier: 验证失败]==]  )
set_tests_properties( [==[KnowledgeVerifier: 验证失败]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeVerifier: 部分通过]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeVerifier: 部分通过]==]  )
set_tests_properties( [==[KnowledgeVerifier: 部分通过]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[KnowledgeVerifier: 空三元组]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[KnowledgeVerifier: 空三元组]==]  )
set_tests_properties( [==[KnowledgeVerifier: 空三元组]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 模拟推理集成]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 模拟推理集成]==]  )
set_tests_properties( [==[Learner: 模拟推理集成]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
add_test( [==[Learner: 反事实推理集成]==] /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda/ai_learning_tests [==[Learner: 反事实推理集成]==]  )
set_tests_properties( [==[Learner: 反事实推理集成]==] PROPERTIES WORKING_DIRECTORY /mnt/d/mayAi/AILearning_v0527/ai-learning-cpp/build-cuda SKIP_RETURN_CODE 4)
set( ai_learning_tests_TESTS [==[Learner: 完整学习循环]==] [==[Learner: 感知循环]==] [==[Learner: 经验学习]==] [==[Learner: 发展阶段]==] [==[Learner: 能力评估]==] [==[Learner: 自主进化]==] [==[Learner: 统计]==] [==[Learner: 保存和加载]==] [==[ModuleRegistry: 注册并获取模块]==] [==[ModuleRegistry: 未注册模块抛异常]==] [==[ModuleRegistry: 直接设置实例]==] [==[ModuleRegistry: has_factory 和 initialized_names]==] [==[ModuleRegistry: clear_instances 保留工厂]==] [==[StatisticalLearner: 基本观察]==] [==[StatisticalLearner: 概念涌现]==] [==[StatisticalLearner: 概念查询]==] [==[StatisticalLearner: 序列预测]==] [==[StatisticalLearner: 意外度]==] [==[StatisticalLearner: 关系涌现]==] [==[StatisticalLearner: 相关概念]==] [==[StatisticalLearner: 统计信息]==] [==[UnifiedReasoningEngine: 基本推理]==] [==[UnifiedReasoningEngine: 直接查询]==] [==[UnifiedReasoningEngine: 概率推理]==] [==[UnifiedReasoningEngine: 多跳推理]==] [==[UnifiedReasoningEngine: 归纳推理]==] [==[UnifiedReasoningEngine: 空知识图谱]==] [==[UnifiedReasoningEngine: 关键词提取]==] [==[TensorOps: 向量加法]==] [==[TensorOps: 向量减法]==] [==[TensorOps: 标量乘法]==] [==[TensorOps: ReLU]==] [==[TensorOps: MSE]==] [==[TensorOps: 余弦相似度]==] [==[TensorOps: 矩阵向量乘法]==] [==[TensorOps: 外积更新]==] [==[TensorOps: clamp]==] [==[HippocampalMemory: 单次编码]==] [==[HippocampalMemory: 按实体检索]==] [==[HippocampalMemory: 容量限制]==] [==[HippocampalMemory: 强度衰减]==] [==[HippocampalMemory: 遗忘弱记忆]==] [==[HippocampalMemory: 增强指定条目]==] [==[HippocampalMemory: get_strongest]==] [==[CorticalMemory: 存储和检索]==] [==[CorticalMemory: 重复存储会增强]==] [==[CorticalMemory: 衰减]==] [==[SleepConsolidation: 完整睡眠周期]==] [==[SleepConsolidation: 弱记忆被遗忘]==] [==[KnowledgeExtractor: 提取中文实体]==] [==[KnowledgeExtractor: 提取关系三元组]==] [==[KnowledgeExtractor: 提取因果关系]==] [==[KnowledgeExtractor: 提取数值事实]==] [==[KnowledgeExtractor: 空文本]==] [==[KnowledgeExtractor: 多个因果关系]==] [==[PredictiveCodingEngine: 构造和基本预测]==] [==[PredictiveCodingEngine: 学习降低误差]==] [==[PredictiveCodingEngine: 好奇心]==] [==[PredictiveCodingEngine: 学习进度初始为 0]==] [==[PredictiveCodingEngine: 状态保存和加载]==] [==[PredictiveCodingEngine: 推理步数记录]==] [==[TextLearner: 从简单文本学习]==] [==[TextLearner: 从因果文本学习]==] [==[TextLearner: 从数值文本学习]==] [==[TextLearner: 学后思考]==] [==[TextLearner: STDP 连接]==] [==[TextLearner: 海马记忆]==] [==[TextLearner: 知识图谱增长]==] [==[TextLearner: 验证反馈]==] [==[TextLearner: 矛盾检测]==] [==[EpisodicMemory: 存储和检索]==] [==[EpisodicMemory: 容量限制]==] [==[EpisodicMemory: 巩固]==] [==[ActivationSpread: 简单扩散]==] [==[ActivationSpread: 衰减效应]==] [==[ActivationSpread: 阈值过滤]==] [==[STDP: LTP 长时程增强]==] [==[STDP: LTD 长时程抑制]==] [==[STDP: 强连接检索]==] [==[STDP: 全局衰减]==] [==[Perception: MultiModalEncoder 构造与基本编码]==] [==[Perception: 单模态编码]==] [==[Perception: 多模态融合编码]==] [==[Perception: 权重更新]==] [==[Perception: 空输入返回零向量]==] [==[Environment: SimpleEnvironment 初始化]==] [==[Environment: step 执行动作]==] [==[Environment: reset 重置环境]==] [==[Environment: 到达目标获得高奖励]==] [==[Environment: configure_for_stage 调整难度]==] [==[Autonomous: Learner 在环境中自主学习]==] [==[Autonomous: 自主学习降低预测误差]==] [==[Autonomous: 巩固在循环中执行]==] [==[Social: SocialAgent 交互]==] [==[Social: 观察伙伴学习]==] [==[Social: 教授其他 Agent]==] [==[Social: 接收知识]==] [==[Social: 统计信息]==] [==[Persistence: save 和 load 状态]==] [==[Persistence: 保存文件格式正确]==] [==[Grounding: 感知聚类创建]==] [==[Grounding: 相似感知合并到同一聚类]==] [==[Grounding: 社会标注接地]==] [==[Grounding: 重复社会标注增强置信度]==] [==[Grounding: 相似概念检索]==] [==[Grounding: 未接地符号返回空]==] [==[Development: 初始阶段为感知运动]==] [==[Development: 预测准确率达标可晋升]==] [==[Development: 词汇量达标可晋升]==] [==[Development: 条件不足不能晋升]==] [==[Development: 逐级晋升到读写]==] [==[Development: 阶段转换记录历史]==] [==[Development: 阶段名称转换]==] [==[Evolver: 能力评估返回所有能力]==] [==[Evolver: 进化后分数应记录]==] [==[Evolver: 弱项识别]==] [==[SimulationReasoning: 场景构建]==] [==[SimulationReasoning: 因果链追踪]==] [==[SimulationReasoning: 反事实推理]==] [==[SimulationReasoning: 表达为自然语言]==] [==[SimulationReasoning: 统计]==] [==[KnowledgeVerifier: 验证通过]==] [==[KnowledgeVerifier: 验证失败]==] [==[KnowledgeVerifier: 部分通过]==] [==[KnowledgeVerifier: 空三元组]==] [==[Learner: 模拟推理集成]==] [==[Learner: 反事实推理集成]==])
