import os
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'learn_wiki.cpp')
lines = []
a = lines.append

a('#include "ai_learning/learning/distributional_semantics.hpp"')
a('#include "ai_learning/learning/embedding_trainer.hpp"')
a('#include <cmath>')
a('#include <cstdio>')
a('#include <chrono>')
a('#include <fstream>')
a('#include <iomanip>')
a('#include <iostream>')
a('#include <string>')
a('#include <vector>')
a('')
a('using namespace ai_learning::learning;')
a('')
a('std::string fmt(long long n) {')
a('    char b[32];')
a('    if(n>=1000000000){snprintf(b,32,"%.1fB",n/1e9);return b;}')
a('    if(n>=1000000){snprintf(b,32,"%.1fM",n/1e6);return b;}')
a('    if(n>=1000){snprintf(b,32,"%.1fK",n/1e3);return b;}')
a('    return std::to_string(n);')
a('}')
a('std::string fmtb(long long b) {')
a('    char buf[32];')
a('    if(b>=1073741824){snprintf(buf,32,"%.2f GB",b/1073741824.0);return buf;}')
a('    if(b>=1048576){snprintf(buf,32,"%.1f MB",b/1048576.0);return buf;}')
a('    return std::to_string(b)+" B";')
a('}')
a('')
a('std::string extract_text(const std::string& line) {')
a('    auto pos = line.find("\\x22text\\x22: \\x22");')
a('    if (pos == std::string::npos) return "";')
a('    pos += 9;')
a('    std::string r; r.reserve(4096);')
a('    bool esc = false;')
a('    for (size_t i = pos; i < line.size(); ++i) {')
a('        char c = line[i];')
a('        if (esc) {')
a('            if(c==110||c==116) r+=32; else r+=c;')
a('            esc = false;')
a('        } else if (c==92) { esc=true; }')
a('        else if (c==34) break;')
a('        else { if(c==10||c==13) r+=32; else r+=c; }')
a('    }')
a('    return r;')
a('}')
a('')
a('std::vector<std::string> list_files(const std::string& dir) {')
a('    std::vector<std::string> out;')
a('    std::string cmd = "dir /s /b \\x22"+dir+"\\\\wiki_*\\x22 2>nul";')
a('    FILE* p = _popen(cmd.c_str(),"r");')
a('    if(!p) return out;')
a('    char buf[1024];')
a('    while(fgets(buf,sizeof(buf),p)) {')
a('        std::string s(buf);')
a('        while(!s.empty()&&(s.back()==10||s.back()==13)) s.pop_back();')
a('        if(!s.empty()) out.push_back(s);')
a('    }')
a('    _pclose(p);')
a('    return out;')
a('}')
a('')
a('float cosine_sim(const std::vector<float>& a, const std::vector<float>& b) {')
a('    float dot=0,na=0,nb=0;')
a('    for(size_t i=0;i<a.size();++i){dot+=a[i]*b[i];na+=a[i]*a[i];nb+=b[i]*b[i];}')
a('    float d=std::sqrt(na)*std::sqrt(nb);')
a('    return d<1e-8f?0.0f:dot/d;')
a('}')
a('')
a('int main(int argc, char* argv[]) {')
a('    using clock = std::chrono::steady_clock;')
a('    std::string wiki_dir = R"(D:\\mayAi\\AILearning_v0527\\parallel-learning\\data\\wiki_zh)";')
a('    if(argc>1) wiki_dir=argv[1];')
a('')
a('    std::cout<<"==================================================\\n";')
a('    std::cout<<"  AILearning - wiki_zh\\n";')
a('    std::cout<<"  PPMI + SGNS\\n";')
a('    std::cout<<"==================================================\\n\\n";')
a('')
a('    auto files = list_files(wiki_dir);')
a('    std::cout<<"[0] Files: "<<files.size()<<"\\n\\n";')
a('    if(files.empty()){std::cerr<<"No files!\\n";return 1;}')
a('')
a('    // Phase 1: PPMI')
a('    std::cout<<"====== Phase 1: PPMI ======\\n";')
a('    auto t1 = clock::now();')
a('')
a('    DistributionalSemanticsConfig dsc;')
a('    dsc.min_cpt_freq = 5;')
a('    dsc.window_size = 8;')
a('    dsc.max_dimensions = 300;')
a('    dsc.ppmi_threshold = 0.3;')
a('    dsc.max_cpts = 100000;')
a('    dsc.use_causal_prior = false;')
a('    DistributionalSemantics ds(dsc);')
a('')
a('    long long total_chars=0, total_articles=0;')
a('    int fdone=0, report=std::max(1,(int)files.size()/20);')
a('')
a('    for(auto& fp: files) {')
a('        std::ifstream fin(fp, std::ios::binary);')
a('        if(!fin) continue;')
a('        std::string line;')
a('        while(std::getline(fin,line)) {')
a('            if(line.empty()||line[0]!=123) continue;')
a('            auto txt=extract_text(line);')
a('            if(txt.empty()) continue;')
a('            ds.learn_from_text(txt);')
a('            total_chars+=(long long)txt.size();')
a('            total_articles++;')
a('        }')
a('        fdone++;')
a('        if(fdone%report==0) {')
a('            auto st=ds.stats();')
a('            std::cout<<"  ["<<100*fdone/(int)files.size()<<"%] "')
a('                <<fdone<<"/"<<files.size()<<" files, "')
a('                <<fmt(total_articles)<<" articles, "')
a('                <<fmt(total_chars)<<" chars, "')
a('                <<st.cpts_represented<<" concepts\\n";')
a('        }')
a('    }')
a('    auto t1e=clock::now();')
a('    double sec1=std::chrono::duration<double>(t1e-t1).count();')
a('    auto ss=ds.stats();')
a('')
a('    std::cout<<"\\n  Phase 1: "<<sec1<<"s\\n";')
a('    std::cout<<"  Articles: "<<fmt(total_articles)<<", Chars: "<<fmtb(total_chars)<<"\\n";')
a('    std::cout<<"  Concepts: "<<ss.cpts_represented<<"\\n";')
a('    std::cout<<"  Dimensions: "<<ss.total_dimensions<<"\\n";')
a('    std::cout<<"  Avg density: "<<std::fixed<<std::setprecision(1)<<ss.avg_vector_density<<"\\n\\n";')
a('')
a('    // Phase 1.5: PPMI eval')
a('    std::cout<<"====== Phase 1.5: PPMI Eval ======\\n";')
a('    auto all_cpts = ds.all_cpts();')
a('    std::cout<<"  Total concepts: "<<all_cpts.size()<<"\\n";')
a('')
a('    std::cout<<"\\n  First 30 multi-char concepts:\\n  ";')
a('    int shown=0;')
a('    for(auto& c: all_cpts) {')
a('        if(shown>=30) break;')
a('        if(c.size()>=6) { std::cout<<c<<" "; shown++; }')
a('    }')
a('    std::cout<<"\\n\\n";')
a('')
a('    std::cout<<"  Pairwise similarity:\\n";')
a('    int pairs=0;')
a('    for(int i=0; i<(int)all_cpts.size()&&pairs<10; i+=2) {')
a('        auto& pa=all_cpts[i], &pb=all_cpts[i+1];')
a('        if(pa.size()<6||pb.size()<6) continue;')
a('        auto sim=ds.similarity(pa,pb);')
a('        std::cout<<"    "<<pa<<" <-> "<<pb<<": "')
a('            <<std::fixed<<std::setprecision(4)<<sim.similarity<<"\\n";')
a('        pairs++;')
a('    }')
a('')
a('    std::cout<<"\\n  Most similar:\\n";')
a('    int qn=0;')
a('    for(auto& w: all_cpts) {')
a('        if(qn>=8) break;')
a('        if(w.size()<6) continue;')
a('        auto top=ds.most_similar(w,5);')
a('        if(top.empty()) continue;')
a('        std::cout<<"    "<<w<<" -> ";')
a('        for(int i=0;i<std::min(5,(int)top.size());++i) {')
a('            if(i) std::cout<<", ";')
a('            std::cout<<top[i].cpt_b<<"("<<std::fixed<<std::setprecision(3)<<top[i].similarity<<")";')
a('        }')
a('        std::cout<<"\\n";')
a('        qn++;')
a('    }')
a('')
a('    std::cout<<"\\n  Clusters (top 5):\\n";')
a('    auto clusters=ds.discover_clusters(0.15);')
a('    for(int i=0;i<std::min(5,(int)clusters.size());++i) {')
a('        auto& cl=clusters[i];')
a('        std::cout<<"    ["<<cl.label<<"] ("<<cl.members.size()<<" members, "')
a('            <<std::fixed<<std::setprecision(3)<<cl.cohesion<<"): ";')
a('        for(int j=0;j<std::min(8,(int)cl.members.size());++j) {')
a('            if(j) std::cout<<", ";')
a('            std::cout<<cl.members[j];')
a('        }')
a('        if(cl.members.size()>8) std::cout<<", ...";')
a('        std::cout<<"\\n";')
a('    }')
a('')
a('    // Phase 2: SGNS')
a('    std::cout<<"\\n====== Phase 2: SGNS ======\\n";')
a('    auto t2=clock::now();')
a('')
a('    EmbeddingTrainerConfig ec;')
a('    ec.embedding_dim=128;')
a('    ec.epochs=3;')
a('    ec.min_count=5;')
a('    ec.neg_samples=5;')
a('    ec.window_size=8;')
a('    ec.learning_rate=0.025;')
a('    ec.seed=42;')
a('    ec.report_interval=50000;')
a('    ec.max_vocab=100000;')
a('    EmbeddingTrainer trainer(ec);')
a('')
a('    trainer.import_vocabulary(all_cpts);')
a('')
a('    long long fed=0, max_feed=200000;')
a('    std::cout<<"  Feeding corpus...\\n";')
a('    for(auto& fp: files) {')
a('        if(fed>=max_feed) break;')
a('        std::ifstream fin(fp,std::ios::binary);')
a('        if(!fin) continue;')
a('        std::string line;')
a('        while(std::getline(fin,line)&&fed<max_feed) {')
a('            if(line.empty()||line[0]!=123) continue;')
a('            auto txt=extract_text(line);')
a('            if(txt.empty()) continue;')
a('            trainer.add_text(txt);')
a('            fed++;')
a('            if(fed%50000==0) std::cout<<"    fed "<<fmt(fed)<<" articles\\n";')
a('        }')
a('    }')
a('    std::cout<<"  Corpus: "<<fmt(fed)<<" articles\\n";')
a('    std::cout<<"  Training...\\n\\n";')
a('')
a('    trainer.set_progress_callback([](const TrainingProgress& p){')
a('        std::cout<<"    E"<<p.epoch<<"/"<<p.total_epochs')
a('            <<" pairs="<<fmt(p.pairs_processed)')
a('            <<" loss="<<std::fixed<<std::setprecision(4)<<p.loss')
a('            <<" lr="<<std::setprecision(5)<<p.current_lr')
a('            <<" "<<std::setprecision(1)<<p.elapsed_seconds<<"s\\n";')
a('    });')
a('')
a('    auto res=trainer.train();')
a('    auto t2e=clock::now();')
a('    double sec2=std::chrono::duration<double>(t2e-t2).count();')
a('')
a('    std::cout<<"\\n  Phase 2: "<<sec2<<"s\\n";')
a('    std::cout<<"  Vocab: "<<res.vocab_size<<"  Dim: "<<res.embedding_dim<<"\\n";')
a('    std::cout<<"  Pairs: "<<fmt(res.total_pairs)<<"\\n";')
a('    std::cout<<"  Loss: "<<std::fixed<<std::setprecision(6)<<res.final_loss<<"\\n";')
a('    std::cout<<"  CUDA: "<<(res.used_cuda?"yes":"no")<<"\\n\\n";')
a('')
a('    if(trainer.is_trained()) {')
a('        std::cout<<"====== Phase 3: Embedding Eval ======\\n";')
a('        std::cout<<"\\n  Dense similarity:\\n";')
a('        int ecnt=0;')
a('        for(int i=0;i<std::min(20,(int)all_cpts.size());i+=2) {')
a('            auto& pa=all_cpts[i],&pb=all_cpts[i+1];')
a('            if(pa.size()<6||pb.size()<6) continue;')
a('            auto va=trainer.get_embedding(pa),vb=trainer.get_embedding(pb);')
a('            if(!va||!vb){std::cout<<"    "<<pa<<" <-> "<<pb<<": (no vec)\\n";continue;}')
a('            float s=cosine_sim(*va,*vb);')
a('            std::cout<<"    "<<pa<<" <-> "<<pb<<": "<<std::fixed<<std::setprecision(4)<<s<<"\\n";')
a('            ecnt++;')
a('        }')
a('')
a('        std::cout<<"\\n  Dense most similar:\\n";')
a('        int q2=0;')
a('        for(auto& w: all_cpts) {')
a('            if(q2>=8) break;')
a('            if(w.size()<6) continue;')
a('            auto top=trainer.most_similar(w,5);')
a('            if(top.empty()) continue;')
a('            std::cout<<"    "<<w<<" -> ";')
a('            for(int i=0;i<std::min(5,(int)top.size());++i) {')
a('                if(i) std::cout<<", ";')
a('                std::cout<<top[i].word<<"("<<std::setprecision(3)<<top[i].similarity<<")";')
a('            }')
a('            std::cout<<"\\n";')
a('            q2++;')
a('        }')
a('')
a('        trainer.save("wiki_embeddings.bin");')
a('        std::cout<<"\\n  Saved: wiki_embeddings.bin\\n";')
a('    }')
a('')
a('    std::cout<<"\\n==================================================\\n";')
a('    std::cout<<"  SUMMARY\\n";')
a('    std::cout<<"==================================================\\n";')
a('    std::cout<<"  Corpus: "<<fmt(total_articles)<<" articles, "<<fmtb(total_chars)<<"\\n";')
a('    std::cout<<"  PPMI concepts: "<<ss.cpts_represented<<"\\n";')
a('    std::cout<<"  PPMI dims: "<<ss.total_dimensions<<"\\n";')
a('    std::cout<<"  Embedding vocab: "<<res.vocab_size<<"\\n";')
a('    std::cout<<"  Embedding dim: "<<res.embedding_dim<<"\\n";')
a('    std::cout<<"  Total time: "<<std::fixed<<std::setprecision(1)<<sec1+sec2<<"s\\n";')
a('    std::cout<<"==================================================\\n";')
a('    return 0;')
a('}')

with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Generated {len(lines)} lines to {out}')
